---
title: "stad37 a3"
output: pdf_document
date: '2022-11-18'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




install.packages("biotools")
install.packages("DescTools")
install.packages("ICSNP")
install.packages("Hotelling")
#Question 1
```{r}
#a)

data <- read.table("profilePotato.txt", header=TRUE)
x <- data
colnames(x) <-c("x1","x2","x3", "method")
xm <- subset(x, method=="1", select=c(x1,x2,x3))
xf <- subset(x, method=="2", select=c(x1,x2,x3))
p <- ncol(xm)
n1 <- nrow(xm)
n2 <- nrow(xf)
xbar1 <- colMeans(xm)
xbar2 <- colMeans(xf)


#Begin the profile plot
var <- c(1,2,3)
plot(var, xbar1, ylim=range(c(2,3)), type="l", col="blue", ylab = "Mean Score", axes = FALSE,)
axis(side =1, at= var)
axis(side =2)
lines(var, xbar2, col="red")

```
```{r}
#b)

###perform profile analysis###

#Test for parallel profiles

S1 <- cov(xm)
S2 <- cov(xf)
Sp <- (1/(n1+n2-2))*((n1-1)*S1+(n2-1)*S2)
C <- matrix(c(-1,0,1,-1,0,1), byrow = FALSE, 2, 3)
c <-C%*%(xbar1-xbar2)
T_sq_parallel <- ((1/n1+1/n2)^(-1))*t(xbar1-xbar2)%*%t(C)%*%solve(C%*%Sp%*%t(C))%*%c
alpha <- 0.05
CritValue_parallel <- (((n1+n2-2)*(p-1))/(n1+n2-p))*qf(1-alpha, p-1, n1+n2-p)
F_parallel <- T_sq_parallel/((((n1+n2-2)*(p-1))/(n1+n2-p)))
p_parallel <- 1-pf(F_parallel, p-1 , n1+n2-p)
cat(T_sq_parallel,CritValue_parallel,F_parallel,p_parallel)

#Now we test for coincident profiles

one <- as.matrix(c(rep(1,p)))
T_sq_coincident <- ((t(one)%*%(xbar1-xbar2))/sqrt((1/n1+1/n2)*(t(one)%*%Sp%*%one)))^2
alpha <- 0.05
CritValue_coincident <- qf(1-alpha, 1, n1+n2-2)
p_coincident <- 1-pf(T_sq_coincident, 1, n1+n2-2 )
cat(T_sq_coincident,CritValue_coincident,p_coincident)

#Next test for level profiles

S <- cov(x[,1:3])
xbar <- colMeans(x[,1:3])
T_sq_level <- (n1+n2)*t(C%*%xbar)%*%solve(C%*%S%*%t(C))%*%(C%*%xbar)
CritValue_level <- (((n1+n2-1)*(p-1))/(n1+n2-p+1))*qf(1-alpha, p-1, n1+n2-p+1)
F_level <- T_sq_level/((((n1+n2-1)*(p-1))/(n1+n2-p+1)))
p_level <- 1-pf(F_level, p-1 , n1+n2-p+1)
cat(T_sq_level,CritValue_level,F_level,p_level)
```

#Question 2
```{r}
library(corpcor)
library(Hotelling)
#a)

library(biotools)

data3 <- read.table("2sample_data.txt",header=TRUE)
xpop1 <- subset(data3, Period=="1")
xpop2 <- subset(data3, Period=="2")
xbar1<-colMeans(xpop1[,1:4])
xbar2<-colMeans(xpop2[,1:4])

print(xbar1)
print(xbar2)


#b)

s1<-cov(xpop1[,1:4]) 
s2<-cov(xpop2[,1:4])
sp<-((nf-1)*Sf+(nm-1)*Sm)/(nf+nm-2)
print(s1)
print(s2)
print(sp)

```
```{r}
#c)
boxM(data3[, 1:4], data3[, "Period"])
alpha=0.05

#given p-val of 0.428 which is greater than alpha=0.05, we can see that we fail to reject the null hypothesis
```
```{r}
#d)
library(DescTools)
xpop1 <- subset(data3, Period=="1")
xpop2 <- subset(data3, Period=="2")
n1 <- nrow(xpop1)
n2 <- nrow(xpop2)
n<-n1+n2
sample1<-xpop1[,1:4] #period 1
sample2<-xpop2[,1:4] #period 2
HotellingsT2Test(sample1,sample2,mu=NULL,test="f")
mean1<-colMeans(sample1) #mean of Period 1
mean2<-colMeans(sample2) #mean of Period 2
Sf<-cov(sample1)
Sm<-cov(sample2)
nf<-nrow(sample1)
nm<-nrow(sample2)
p<-ncol(sample1)
delta0<-c(0,0)
sp<-((nf-1)*Sf+(nm-1)*Sm)/(nf+nm-2)
T_sq <- t(mean1-mean2-delta0)%*%solve((1/nf+1/nm)*sp)%*%(mean1-mean2-delta0)
criticalValue <- (((n-2)*p)/(n-p-1))*qf(0.95,p, nf+nm-p-1 )#reject null hypothesis since T_sq > crit val
pval<-pf(qf(0.95,p,nf+nm-p-1),4,55,lower.tail=FALSE,)
print(pval)
print(T_sq)
print(criticalValue)

solve((((1/n1)*Sf)+((1/n2)*Sm)))%*%(mean1-mean2)
```
```{r}
#e)

xpop1 <- subset(data3, Period=="1")
xpop2 <- subset(data3, Period=="2")
n1 <- nrow(xpop1)
n2 <- nrow(xpop2)
n<-n1+n2
g<-2
p<-4
xbar1<-colMeans(xpop1[,1:4])
xbar2<-colMeans(xpop2[,1:4])
s1<-cov(xpop1[,1:4])
s2<-cov(xpop2[,1:4])
T <- (n-1)*cov(data3[,1:4])
W <- (n1-1)*s1+(n2-1)*s2
B <- T-W
alpha <- 0.05
t <- qt(1-alpha/(p*g*(g-1)),df=n-g)
for ( i in 1:p ){
 LCI12 <- (xbar1[i]-xbar2[i])-t*sqrt(W[i,i]/(n-g)*(1/n1+1/n2))
 UCI12 <- (xbar1[i]-xbar2[i])+t*sqrt(W[i,i]/(n-g)*(1/n1+1/n2))
 cat("Bon SCI for mu1[",i,"]-mu2[",i,"] = (",LCI12,",",UCI12,")\n",sep="")   
 
}

#now we calculate SCI

dxbar<-xbar1-xbar2
spd<-diag(sp)
c<-sqrt(criticalValue)
SE <- sqrt(spd*(1/nf+1/nm))
CI_L_sim <- dxbar-c*SE
CI_U_sim <- dxbar+c*SE
CI_L_Bon <- dxbar-qt(1-0.05/(2*p),nf+nm-2)*SE
CI_U_Bon <- dxbar+qt(1-0.05/(2*p),nf+nm-2)*SE
CIs <- cbind(dxbar, CI_L_sim, CI_U_sim, CI_L_Bon, CI_U_Bon)
colnames(CIs) <- c("xbar m-f", "sim Lower", "sim Upper", "Bon Lower", "Bon Upper")
print(CIs)
```
```{r}
#f)
n<-n1+n2
T<-(n-1)*cov(data3[,1:4])
s1<-cov(xpop1[,1:4])
s2<-cov(xpop2[,1:4])
W<-(n1-1)*s1+(n2-1)*s2
B<-T-W
lambda<-det(W)/(det(B+W))
g<-2 #number of populations, in our case, we have two
p<-4 #number of variables, in our case, we have four
rootlambda<-sqrt(lambda)
teststat<-((n-p-1)/p)*((1-lambda)/lambda)
CritValue <- qf(1-0.05,p,n-p-1) #since we have p>=1 var and g=2 groups, we use F(p,summation of n_l - p -1)
print(teststat)
print(CritValue)

x14<-as.matrix(data3[,1:4])
pop<-factor(data3$Period)
fit <- manova(x14~pop)
result<-summary(fit, test="Wilks") #p-value is the same
print(result)
```

#Question 3
```{r}
#a)

data2 <- read.table("t6_17.txt", header=TRUE)
n <- 12
p<-3
g<-2
b<-3
colnames(data2) <- c("fac1", "fac2", "x1", "x2", "x3")
fac1 <- factor(data2$fac1)
fac2 <- factor(data2$fac2)
x345 <- as.matrix(data2[,3:5])
fit <- manova(x345~fac1*fac2)
moreinfo <- summary(fit)
SSPfac1 <- moreinfo$SS[1]
SSPfac2 <- moreinfo$SS[2]
SSPint<-moreinfo$SS[3]
SSPres<-moreinfo$SS[4]
print(SSPfac1)
print(SSPfac2)
print(SSPint)
print(SSPres)

#b)

SSPfac1m <- SSPfac1$fac1
SSPfac2m <- SSPfac2$fac2
SSPintm <- SSPint$`fac1:fac2`
SSPresm <- SSPres$Residuals
Lambda1 <- det(SSPresm)/det(SSPfac1m+SSPresm)
Lambda2 <- det(SSPresm)/det(SSPfac2m+SSPresm)
Lambda_int <- det(SSPresm)/det(SSPintm+SSPresm)

```